services:
  4l-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 4l-site
    restart: unless-stopped
    ports:
      - "8081:3000"
    environment:
      - NODE_ENV=production
